name: linting, testing, building
on: [push, pull_request]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '17'
            - name: install modules
              run: npm install
            - name: build production project
              run: npm run build:prod
            - name: linting typescript
              run: npm run lint:ts
            - name: linting css
              run: npm run lint:scss
            - name: unit testing
              run: npm run test:unit
            - name: screenshot testing
              run: npm run test:ui:ci
